{ pkgs, ... }:
{
  home.packages = [ pkgs.hypridle ];

  xdg.configFile."hypr/hypridle.conf".text = ''
    # generated by home-manager
    general {
    	lock_cmd = pidof hyprlock || hyprlock
    }

    listener {
    	timeout = 900
    	on-timeout = loginctl lock-session
    }

    listener {
    	timeout = 1800
    	on-timeout = systemctl suspend
    }
  '';
}
