{ config, lib, ... }:
let
  colors = config.stylix.base16Scheme;
  themeUtils = import ../../../themes/utils.nix { inherit lib; };
  strip = lib.removePrefix "#";
  rgba = hex: themeUtils.toRgba { inherit hex; };
  alpha = hex: "${strip hex}ff";
  accent = colors.base0D;
  foreground = colors.base05;
  background = colors.base00;
  currentLine = colors.base03;
  foregroundAlpha = alpha foreground;
  accentAlpha = alpha accent;
  font = config.stylix.fonts.monospace.name;
in
{
  xdg.configFile."hypr/hyprlock.conf".text = ''
    # generated by home-manager
    $accent = ${rgba accent}
    $accentAlpha = ${accentAlpha}
    $background = ${rgba background}
    $current_line = ${rgba currentLine}
    $foreground = ${rgba foreground}
    $foregroundAlpha = ${foregroundAlpha}
    $font = ${font}
    $red = ${rgba colors.base08}
    $yellow = ${rgba colors.base0A}

    # GENERAL
    general {
        disable_loading_bar = true
        hide_cursor = true
    }

    # BACKGROUND
    background {
        monitor =
        path = ${config.xdg.dataHome}/wallpapers/shaded-landscape.png
        blur = false
        color = $background
    }

    # TIME
    label {
        monitor =
        text = cmd[update:30000] echo "$(date +"%R")"
        color = $foreground
        font_size = 90
        font_family = $font
        position = -30, 0
        halign = right
        valign = top
    }

    # DATE
    label {
        monitor =
        text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
        color = $foreground
        font_size = 25
        font_family = $font
        position = -30, -150
        halign = right
        valign = top
    }

    # USER AVATAR
    image {
        monitor =
        path = ~/.face
        size = 100
        border_color = $accent

        position = 0, 75
        halign = center
        valign = center
    }

    # INPUT FIELD
    input-field {
        monitor =
        size = 300, 60
        outline_thickness = 4
        dots_size = 0.2
        dots_spacing = 0.2
        dots_center = true
        outer_color = $accent
        inner_color = $background
        font_color = $foreground
        fade_on_empty = false
        placeholder_text = <span foreground="##$foregroundAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
        hide_input = false
        check_color = $accent
        fail_color = $red
        fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
        capslock_color = $yellow
        position = 0, -35
        halign = center
        valign = center
    }
  '';
}
